### ISSUE TITLE
GitHub Pages deployment is not stable

### ISSUE THREAD

**Issue by maschmi** [maschmi/angular-playground#5]

**Comment by maschmi** [comment]
Somehow the app is reachable under https://maschmi.github.io/angular-playground/angular-playground/

* It is not working when no base ref is set
* It shows a strange error
`Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'angular-playground' Error: Cannot match any routes. URL Segment: 'angular-playground' at ke.noMatchError (https://maschmi.github.io/angular-playground/main.e1625b42d646bd0aa364.js:1:538317) at l.selector (https://maschmi.github.io/angular-playground/main.e1625b42d646bd0aa364.js:1:538036) at l.error (https://maschmi.github.io/angular-playground/main.e1625b42d646bd0aa364.js:1:50143) at o._error (https://maschmi.github.io/angular-playground/main.e1625b42d646bd0aa364.js:1:121125) at o.error (https://maschmi.github.io/angular-playground/main.e1625b42d646bd0aa364.js:1:120922) at o._error (https://maschmi.github.io/angular-playground/main.e1625b42d646bd0aa364.js:1:121125) at o.error (https://maschmi.github.io/angular-playground/main.e1625b42d646bd0aa364.js:1:120922) at o._error (https://maschmi.github.io/angular-playground/main.e1625b42d646bd0aa364.js:1:121125) at o.error (https://maschmi.github.io/angular-playground/main.e1625b42d646bd0aa364.js:1:120922) at a._error (https://maschmi.github.io/angular-playground/main.e1625b42d646bd0aa364.js:1:121125)`
